# Generated by Django 5.2.12 on 2026-03-03 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('basic', 'Basic Shield'), ('standard', 'Standard Shield'), ('premium', 'Premium Shield')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('base_weekly_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weekly_coverage', models.DecimalField(decimal_places=2, help_text='Max payout per week in INR', max_digits=10)),
                ('daily_income_coverage_pct', models.IntegerField(default=70, help_text='% of daily income covered')),
                ('max_claim_days_per_week', models.IntegerField(default=3, help_text='Max claimable days per week')),
                ('covers_weather', models.BooleanField(default=True)),
                ('covers_pollution', models.BooleanField(default=True)),
                ('covers_civil_unrest', models.BooleanField(default=False)),
                ('covers_platform_outage', models.BooleanField(default=False)),
                ('waiting_period_hours', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['base_weekly_premium'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('risk_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claims_made', models.IntegerField(default=0)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment'), ('lapsed', 'Lapsed')], default='pending', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('risk_score_at_creation', models.FloatField(default=50.0)),
                ('city_at_creation', models.CharField(blank=True, max_length=100)),
                ('zone_at_creation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.insuranceplan')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city_factor', models.FloatField(default=1.0)),
                ('zone_factor', models.FloatField(default=1.0)),
                ('season_factor', models.FloatField(default=1.0)),
                ('historical_claims_factor', models.FloatField(default=1.0)),
                ('shift_factor', models.FloatField(default=1.0)),
                ('vehicle_factor', models.FloatField(default=1.0)),
                ('experience_factor', models.FloatField(default=1.0)),
                ('weather_forecast_factor', models.FloatField(default=1.0)),
                ('aqi_forecast_factor', models.FloatField(default=1.0)),
                ('final_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('model_version', models.CharField(default='v1.0-rule-based', max_length=50)),
                ('calculation_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_calculations', to='policies.policy')),
            ],
        ),
    ]
