# Generated by Django 5.2.12 on 2026-03-03 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisruptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('extreme', 'Extreme')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zones_affected', models.JSONField(default=list)),
                ('measured_value', models.FloatField(help_text='Actual measured value that triggered this')),
                ('data_source', models.CharField(help_text='API source of the data', max_length=100)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours_lost', models.FloatField(default=4, help_text='Estimated working hours lost')),
                ('auto_claims_generated', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_start'],
            },
        ),
        migrations.CreateModel(
            name='DisruptionTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('heavy_rain', 'Heavy Rainfall'), ('extreme_heat', 'Extreme Heat'), ('severe_pollution', 'Severe Air Pollution (AQI)'), ('flooding', 'Flooding / Waterlogging'), ('cyclone', 'Cyclone Warning'), ('civil_unrest', 'Civil Unrest / Curfew'), ('platform_outage', 'Platform Outage')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('threshold_value', models.FloatField(help_text='Numeric threshold to trigger')),
                ('threshold_unit', models.CharField(help_text='e.g., mm/hr, °C, AQI index', max_length=30)),
                ('threshold_comparison', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('gte', '>='), ('lte', '<='), ('eq', '=')], default='gte', max_length=5)),
                ('payout_percentage', models.IntegerField(default=70, help_text='% of daily income to pay out')),
                ('cities_affected', models.JSONField(default=list, help_text='List of affected city names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trigger_type'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=20, unique=True)),
                ('disruption_type', models.CharField(choices=[('heavy_rain', 'Heavy Rainfall'), ('extreme_heat', 'Extreme Heat'), ('severe_pollution', 'Severe Air Pollution (AQI)'), ('flooding', 'Flooding / Waterlogging'), ('cyclone', 'Cyclone Warning'), ('civil_unrest', 'Civil Unrest / Curfew'), ('platform_outage', 'Platform Outage')], max_length=30)),
                ('initiation_type', models.CharField(choices=[('automatic', 'Automatic (Parametric Trigger)'), ('manual', 'Manual (Worker Submitted)')], default='automatic', max_length=20)),
                ('claim_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('claim_city', models.CharField(max_length=100)),
                ('claim_zone', models.CharField(blank=True, max_length=100)),
                ('claim_latitude', models.FloatField(blank=True, null=True)),
                ('claim_longitude', models.FloatField(blank=True, null=True)),
                ('estimated_hours_lost', models.FloatField(default=0)),
                ('estimated_income_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fraud_score', models.FloatField(default=0, help_text='AI fraud score 0-100')),
                ('fraud_flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('auto_initiated', 'Auto-Initiated'), ('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid Out'), ('flagged', 'Flagged for Fraud')], default='auto_initiated', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('weather_data_snapshot', models.JSONField(default=dict)),
                ('aqi_data_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('disruption_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.disruptionevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='disruptionevent',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='claims.disruptiontrigger'),
        ),
    ]
